version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: ~/repo
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: "true"
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
    steps:
      - checkout
      - run: dotnet restore SharpSettings.sln
      - run: dotnet build src/SharpSettings/SharpSettings.csproj
  deploy-pre:
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: "true"
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
    steps:
      - checkout
      - run:
          command: |
            echo 'export RELEASE_VERSION=${CIRCLE_TAG}.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            source $BASH_ENV
      - run: dotnet restore SharpSettings.sln
      - run: dotnet pack src/SharpSettings/SharpSettings.csproj -o ../../nupkgs --include-symbols
      # - run: dotnet nuget push nupkgs/SharpSettings.$(RELEASE_VERSION).symbols.nupkg -k ${NUGET_API_KEY} -s nuget.org
  deploy-release:
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT: "true"
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
    steps:
      - checkout
      - run:
          command: |
            echo 'export RELEASE_VERSION=${CIRCLE_TAG}.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            source $BASH_ENV
      - run: dotnet restore SharpSettings.sln
      - run: dotnet pack src/SharpSettings/SharpSettings.csproj -o ../../nupkgs --include-symbols
      # - run: dotnet nuget push nupkgs/SharpSettings.$(RELEASE_VERSION).symbols.nupkg -k ${NUGET_API_KEY} -s nuget.org

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-pre:
          requires: 
            - build
          filters:
            branches:
              only: master
            tags:
              only: /[0-9]+(\.[0-9]+)*-pre/
      - deploy-release:
          requires: 
            - build
          filters:
            branches:
              only: master
            tags:
              only: /[0-9]+(\.[0-9]+)*/