version: 2

jobs:
  - build:
      filters:
        branches:
          only: master
      docker:
        - image: microsoft/dotnet:sdk
      working_directory: ~/repo
      environment:
        - DOTNET_CLI_TELEMETRY_OPTOUT: "true"
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
      steps:
        - checkout
        - run: dotnet restore SharpSettings.sln
        - run: dotnet build src/SharpSettings/SharpSettings.csproj

  - deploy:
      filters:
        branches:
          only: master
        tags:
          only: /[0-9]+(\.[0-9]+)*/
      docker:
        - image: microsoft/dotnet:sdk
      environment:
        - DOTNET_CLI_TELEMETRY_OPTOUT: "true"
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
        - RELEASE_VERSION: ${CIRCLE_TAG}.${CIRCLE_BUILD_NUM}
      steps:
        - checkout
        - run: dotnet restore SharpSettings.sln
        - run: dotnet pack src/SharpSettings/SharpSettings.csproj -o ../../nupkgs --include-symbols
        # - run: dotnet nuget push nupkgs/SharpSettings.$(RELEASE_VERSION).symbols.nupkg -k ${NUGET_API_KEY} -s nuget.org